// Copies in-class code into the notebook as read-only source pages.
//
// For every entry in code-sources.json this script READS the original course
// folder and WRITES a Markdown page per file under docs/code/<slug>/. The
// original folders are never modified. docs/code/ is fully generated: it is
// deleted and rebuilt on every run, so never hand-edit anything inside it.
//
// Usage:  npm run sync-code
//         COURSE_DIR=/path/to/SI679 npm run sync-code

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const courseDir = path.resolve(process.env.COURSE_DIR ?? path.join(repoRoot, '..'));
const outRoot = path.join(repoRoot, 'docs', 'code');
const { sources } = JSON.parse(fs.readFileSync(path.join(repoRoot, 'code-sources.json'), 'utf8'));

const SKIP_DIRS = new Set(['node_modules', '.git', '.github', 'dist', 'coverage', '.vscode']);
const SKIP_FILES = new Set(['package-lock.json', '.classroom50.yaml', '.gitkeep', '.DS_Store', '.gitignore']);
const LANG = { '.ts': 'ts', '.mts': 'ts', '.js': 'js', '.mjs': 'js', '.json': 'json', '.md': 'md' };

// Folder order on the index pages: config and docs first, then src/.
const rank = (rel) => (rel.includes('/') ? 1 : 0);

function walk(dir, base = dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) files.push(...walk(full, base));
    } else if (!SKIP_FILES.has(entry.name) && LANG[path.extname(entry.name)] && !entry.name.endsWith('.map')) {
      files.push(path.relative(base, full).split(path.sep).join('/'));
    }
  }
  return files;
}

// `src/books-router.ts` -> `src/books-router-ts`, so VitePress treats the link
// as a page rather than as a static .ts asset.
const pageSlug = (rel) => rel.replace(/\.(?=[^/]+$)/g, '-').replace(/^\.+/, '');

// A fence longer than any backtick run in the file, so READMEs with their own
// code blocks cannot close ours early.
function fenceFor(text) {
  const longest = Math.max(0, ...(text.match(/`+/g) ?? []).map((run) => run.length));
  return '`'.repeat(Math.max(3, longest + 1));
}

fs.rmSync(outRoot, { recursive: true, force: true });
fs.mkdirSync(outRoot, { recursive: true });

const summary = [];
for (const src of sources) {
  const srcDir = path.join(courseDir, src.from);
  if (!fs.existsSync(srcDir)) {
    console.warn(`! skipped ${src.slug}: ${srcDir} not found`);
    continue;
  }
  const files = walk(srcDir).sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));

  for (const rel of files) {
    const text = fs.readFileSync(path.join(srcDir, rel), 'utf8').replace(/\s+$/, '');
    const fence = fenceFor(text);
    const lang = LANG[path.extname(rel)];
    const page = [
      '---',
      `title: ${JSON.stringify(`${rel} · ${src.label}`)}`,
      'editLink: false',
      '---',
      '',
      `# \`${rel}\``,
      '',
      `From **${src.label}** · original: \`${src.from}/${rel}\` · [all files in this project](/code/${src.slug}/)`,
      '',
      `${fence}${lang}:line-numbers`,
      text,
      fence,
      '',
    ].join('\n');
    const outFile = path.join(outRoot, src.slug, `${pageSlug(rel)}.md`);
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, page);
  }

  const list = files.map((rel) => `- [\`${rel}\`](./${pageSlug(rel)})`).join('\n');
  fs.writeFileSync(
    path.join(outRoot, src.slug, 'index.md'),
    `---\ntitle: ${JSON.stringify(src.label)}\n---\n\n# ${src.label}\n\nSynced from \`${src.from}/\`. These are copies; the original folder is untouched.\n\n${list}\n`,
  );
  summary.push({ ...src, count: files.length });
  console.log(`✓ ${src.slug.padEnd(14)} ${String(files.length).padStart(3)} files  ← ${src.from}`);
}

const rows = summary.map((s) => `| [${s.label}](./${s.slug}/) | \`${s.from}/\` | ${s.count} |`).join('\n');
fs.writeFileSync(
  path.join(outRoot, 'index.md'),
  `---\ntitle: Source code\n---\n\n# Source code\n\nRead-only copies of the in-class code, regenerated by \`npm run sync-code\`.\n\n| Project | Original folder | Files |\n|---|---|---|\n${rows}\n`,
);
